### ISSUE TITLE
VideoFrameBuffer objects doesn't freeing correctly

### ISSUE THREAD

**Issue by chainikdn** [AviSynth/AviSynthPlus#49] opened 2014-10-25 14:09 UTC
http://forum.doom9.org/showthread.php?p=1697682#post1697682

In ScriptEnvironment::~ScriptEnvironment() frame->vfb deleted only if frame->vfb->refcount==0 which is not always true.

Proposed change is to delete VideoFrame::vfb ONLY in VideoFrame::DESTRUCTOR() regardless of its refcount value.

It's working as expected as the only place where VideoFrameBuffer objects are created is in ScriptEnvironment::AllocateFrame(). In fact it'll be a good idea to move VideoFrameBuffer creating to VideoFrame constructor.

**Comment by pylorak** [comment] 2015-03-07 20:56
The proposed solution won't work, and there is also nothing wrong with the current checking for refcount==0. More explanation for both my claims (and for why the current way things are should work) can be found in these posts:
http://forum.doom9.org/showpost.php?p=1712444&postcount=869
http://forum.doom9.org/showpost.php?p=1712447&postcount=870

**Comment by pylorak** [comment] 2015-03-09 20:28
Duplicate of issue #50. Continuing discussion there.

**Closed by pylorak** 2015-03-09 20:28 UTC
