### ISSUE TITLE
Merge problem with interleaved color formats

### ISSUE THREAD

**Issue by raffriff42** [AviSynth/AviSynthPlus#102] opened 2016-10-07 01:59 UTC
In YV12/YV16/YV24/Y8, all is good, but -

```
A=Colorbars ## (RGB32)
B=A.Invert
return Merge(A, B, weight=254.0/255.0) ## output = 100% 'A'
return Merge(A, B, weight=254.5/255.0) ## output = 100% 'B'
```

In RGB24 or YUY2, blending works, but the output has vertical stripe artifacts.

AVS 2.61 does not have this issue.

**Comment by qyot27** [comment] 2016-10-07 02:32
Which version of AviSynth+ are you using?  r2172, r1576, some other in-between version?  A build from pinterf's HBD fixes in pull #101?

**Comment by qyot27** [comment] 2016-10-07 02:46
I can't reproduce this with r2275 (pull #101, more or less), so I think this may have been caught and fixed already, there's just not a public build available that contains the fix.

**Comment by raffriff42** [comment] 2016-10-07 13:15
_>Which version of AviSynth+ are you using?_
Sorry - r2172, x86, on Win 8.1 x64
If fixed already, great.

**Comment by pinterf** [comment] 2016-10-10 11:03
I think this was fixed in 
https://github.com/AviSynth/AviSynthPlus/pull/101/commits/0f04e5f667da8d23d3640af06ae4d49f2bcc0278
in new line number 1010

**Closed** 2020-03-05 12:14 UTC
