### ISSUE TITLE
Animate bug. Zero crossing.

### ISSUE THREAD

**Issue by ewgeniktomsk** [AviSynth/AviSynthPlus#293] opened 2022-07-19 00:56 UTC
We are trying to move the text vertically. From y=10 to y=-10. When passing through 0 text appears in the center of the screen.

```
BlankClip(length=50, width=72, height=40)
	Animate(0,50,"Subtitle", \
	"Text1\nText2",36,10,0,50,"Arial",24,$FFFF00,0,5,0,-1, \
	"Text1\nText2",36,-10,0,50,"Arial",24,$FFFF00,0,5,0,-1)
```

Tested on AviSynth 2.60, AviSynth+ 3.7.2
![zina](https://user-images.githubusercontent.com/109562903/179871853-d51613bb-ff6f-4c05-a7b6-d32b9430da88.gif)

**Comment by pinterf** [comment] 2022-07-20 20:19
Thanks for the report, in rest of July I'm on PC-less holiday, I can check the issue later.

**Comment by qyot27** [comment] 2022-07-20 21:54
Quasi-related, is that on Linux that example script will cause a segfault because a font that isn't installed is specified.  Changing it to the internal Terminus font resolves it.

Unfortunately, I'm not seeing this bug happen on Ubuntu, even once I massaged it enough to actually *see* the `Text1` line by adjusting the start position to 25 (which is pretty close to the gif provided by OP), and then even more dramatically to 50 (with `Text1` almost at the bottom of the frame, so you can see both it and `Text2` scroll past the 0 line).  In both cases, it scrolled past 0 and didn't flash back to `Text1` again.

**Comment by ewgeniktomsk** [comment] 2022-07-21 01:48
I will not be too lazy to install Ubuntu and check. I'll let you know the result.
By the way, the problem appears only at a slow text speed. Apparently, at high speed, the text simply skips the fatal mark. So in order to get a bug, the start and end positions should be closer to 0.

**Comment by pinterf** [comment] 2022-08-01 14:14
Reproduced. Subtitle - when y=-1 is passed (which is reached at frame 28 during Animate 10->-10 interpolation) - has a special internal meaning, which prevents using this exact y coordinate. Fix is in progress.

**Comment by pinterf** [comment] 2022-08-01 15:28
> Quasi-related, is that on Linux that example script will cause a segfault because a font that's not available is specified. Changing it to the internal Terminus font* resolves it.

This bug is found as well.

**Closed** 2022-08-03 12:23 UTC
