### ISSUE TITLE
overlay mask bug

### ISSUE THREAD

**Issue by realfinder** [AviSynth/AviSynthPlus#255] opened 2022-01-20 20:43 UTC
as it said here https://forum.doom9.org/showthread.php?t=183710

**Comment by pinterf** [comment] 2022-01-21 09:07
Explanation in 
https://forum.doom9.org/showthread.php?p=1961818#post1961818

**Comment by pinterf** [comment] 2022-01-21 09:09
In my opinion this is not a bug, integer implementation may need exact explanation in documentation.
Or one would use 32 bit float format instead.

**Comment by realfinder** [comment] 2022-01-21 19:14
thanks, so vs Overlay is slower, right?

**Comment by pinterf** [comment] 2022-01-27 14:27
Eh, this turned into a one-week work, including reconstruction of the old ugly codebase and rewriting the all the stuff and added AVX2 as well.
Now I have benchmarks as well, it seems that the accurate new 8 bit basic (mask=yes, opacity=1.0) Overlay is slower (480fps vs 550fps - AVX2, 305 vs 550fps for pre-AVX2 processors)
But all the other cases - when opacity is <1.0 or bit depth>=10 we got a significant speed boost.

**Comment by pinterf** [comment] 2022-02-08 14:12
Maskless blend is broken

**Comment by pinterf** [comment] 2022-02-08 14:15
Maskless blend regression is fixed via [6884b1c](https://github.com/AviSynth/AviSynthPlus/commit/6884b1cdd772c578a06d645491f05557ec1b3b6f)

**Closed by pinterf** 2022-02-08 14:15 UTC
